from os.environ import get

API_ID = get("API_ID", 123)
API_HASH = get("API_HASH", None)
ALLOW_CHATS = get("ALLOW_CHATS", True)
ALLOW_EXCL = get("ALLOW_EXCL", False)
CASH_API_KEY = get("CASH_API_KEY", None)
DB_URI = get("DATABASE_URL")
DEL_CMDS = bool(get("DEL_CMDS", False))
EVENT_LOGS = get("EVENT_LOGS", None)
INFOPIC = bool(get("INFOPIC", "True"))
LOAD = get("LOAD", "").split()
MONGO_DB_URI = get("MONGO_DB_URI", None)
NO_LOAD = get("NO_LOAD", "").split()
START_IMG = get("START_IMG", "https://telegra.ph/file/b84e865d639912ee28f73.jpg")
STRICT_GBAN = bool(get("STRICT_GBAN", True))
SUPPORT_CHAT = get("SUPPORT_CHAT", "LegendBot_OP")
TEMP_DOWNLOAD_DIRECTORY = get("TEMP_DOWNLOAD_DIRECTORY", "./")
TOKEN = get("TOKEN", None)
TIME_API_KEY = get("TIME_API_KEY", None)
WORKERS = int(get("WORKERS", 8))
OWNER_ID = int(get("OWNER_ID", None))
BL_CHATS = set(int(x) for x in get("BL_CHATS", "").split())
DRAGONS = set(int(x) for x in get("DRAGONS", "").split())
DEV_USERS = set(int(x) for x in get("DEV_USERS", "").split())
DEMONS = set(int(x) for x in get("DEMONS", "").split())
TIGERS = set(int(x) for x in get("TIGERS", "").split())
WOLVES = set(int(x) for x in get("WOLVES", "").split())
